image: node:latest


stages:
  - build
  - deploy


build:
  stage: build
  script:
    - npm install
    - CI=false npm run build
  artifacts:
    paths:
      - build

deploy:
  stage: deploy
  image: amazonlinux:latest
  timeout: 4 minutes 
  before_script:
    - yum update -y
    - yum install -y aws-cli
    - aws --version

  script:
    - aws s3 sync build/ s3://task-manager-system-frontend-2 --delete

  only:
    - main
